services:
  - type: web
    name: bail-api
    env: python
    region: singapore
    plan: free
    buildCommand: ""
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000
    workingDir: api
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
